name: Update README Progress

on:
  push:
    branches:
      - main  # veya 'master'
    paths:
      - 'progress.yml' # Sadece progress.yml değiştiğinde çalışsın
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      - name: Run README update script
        run: python update_readme.py

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          # Değişiklik varsa commit at
          git diff --quiet --staged || git commit -m "docs: README ilerlemesini otomatik güncelle"
          git push